### PR TITLE
feat(preset): add dynamic preset loading

### PR DESCRIPTION
**Pull request by tamascsaba**
It possible load dynamic preset js.

Example:
```
conventional-changelog -p ./presets/custom -i CHANGELOG.md -w -r 0
conventional-changelog -p /foo/bar/presets/custom -i CHANGELOG.md -w -r 0
```
and the default behavior is work to (load conventional-changelog/presets/...):
```
conventional-changelog -p angular -i CHANGELOG.md -w -r 0
```

### CODE REVIEW

**Comment by tamascsaba** [comment]
Upps, in node 0.10 path has no method parse :(

**Comment by stevemao** [comment]
I think its more important to solve #113 and #100

**Comment by tamascsaba** [comment]
Sorry, but I don't understand the couple whit this issues. It does not concern my use cases.

**Comment by tamascsaba** [comment]
I will make comment this issues/discussions, as soon as possible.

**Comment by stevemao** [comment]
Sorry if they are not obvious. In #100 I stated that the current CLI flags are not good and the purpose of preset is for people to load the preset of a popular project but not to customise it (if the flags are good enough we can config everything much easier).

**Comment by tamascsaba** [comment]
Thanks for the answer. I understand it. You are right. My use case: Generate debian changelog, but templates are hard coded to presets. What do you think about: templateFolder flag, which whit h can you modify the default templates?

**Comment by tamascsaba** [comment]
@stevemao ?? templateFolder flag??

**Comment by stevemao** [comment]
a template flag might be good. As I said this really depends on #100. Would you like to work on #100 if you can?

**Comment by stevemao** [comment]
The conversation here is a sub set of 
> Also we should probably remove --raw-commits-opts, --parser-opts and --writer-opts and expose useful options of them with each single flag. --context can still be a json file.

**Comment by stevemao** [comment]
fixed by https://github.com/stevemao/conventional-changelog-core/commit/85fd9d9be52b88c6f79131e3095c0ef571a1b004

**Comment by tamascsaba** [comment]
Nice, thx ☺

**Pull request closed without merging**
