### PR TITLE
chore(pkgRepo): move version before getPkgRepo

### LINKED ISSUE #74: Version not parsed from package.json if "repository" field not set in file.
The issue occurs on [line 88 of index.js](https://github.com/ajoslin/conventional-changelog/blob/master/index.js#L88). `getPkgRepo` fails if there is no `repository` information, which prevents the version information from being added to the `context` object, causing blank values in the changelog output. 

I'll see if I can get a PR out for this.

Steps to recreate:
1. Have an NPM repository without a `repository` field:
```
{
  "name": "my-package",
  "version": "1.0.1",
}
```
2. Run `conventional-changelog`
3. See that output does not pick up `version` information

### PR DESCRIPTION
**Pull request by klamping**
Closes #74 

See steps to recreate in issue.

### CODE REVIEW

**Comment by stevemao** [comment]
:+1: It would be great if you can add a test for this?

**Comment by klamping** [comment]
I'll see what I can do. :)

**Comment by stevemao** [comment]
Thanks. You could just add a package.json with only a version.

**Comment by stevemao** [comment]
I'm adding tests now

**Comment by klamping** [comment]
Great, thanks for getting the tests taken care of. I had an event I had to go with so didn't have time.

:+1:

**Pull request closed without merging**
