### PR TITLE
docs(README): add info about running tests

### PR DESCRIPTION
**Pull request by marcin-wosinek**
I didn't work with mocha before, and I found that information missing.

### CODE REVIEW

**Comment by stevemao** [comment]
I think it might be better to make mocha as a dev dep

**Comment by marcin-wosinek** [comment]
I belief doc part is still relevant - without mocha installed globally & available from PATH we are still getting errors

**Comment by stevemao** [comment]
This should be fixed. Can you try the master branch? If it still occurs let us know. Thanks.

**Comment by marcin-wosinek** [comment]
ah my bad. after checkout & reinstall it works as expected. Great, thanks:)

**Pull request closed without merging**
