### PR TITLE
fix(writeLog): fix require statement for Writer

### PR DESCRIPTION
**Pull request by adam-beck**

### CODE REVIEW

**Comment by stevemao** [comment]
Thank you. :+1:

**Comment by stevemao** [comment]
Hi @ajoslin , Can you enable travis on https://travis-ci.org? Before this was merged it passed tests on mac but would fail on linux. So this would have been fixed before we release v0.0.13. Thanks.

**Comment by ajoslin** [comment]
Enabled.

**Comment by stevemao** [comment]
Thanks @ajoslin .

**Pull request merged**
